spring.application.name=eagle-bank-api

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:eaglebank

jwt.secret=anytwohundredandfiftysixbitandabovesecretworkshere
jwt.expiry-hours=24